name-template: "Example title - v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Breaking changes"
    labels:
      - "breaking"
  - title: "Bug fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Translation"
    labels:
      - "translation"
  - title: "Dependencies"
    collapse-after: 2
    labels:
      - "dependencies"
      - "dependency"
  - title: "Maintenance"
    label: "maintenance"
  - title: "Code quality and optimizations"
    label: "code quality"
  - title: "Development tools"
    labels:
      - "development tools"
      - "dev-tools"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads-pre/$OWNER/$REPOSITORY/v$RESOLVED_VERSION/total.svg)](https://github.com/$OWNER/$REPOSITORY/releases/v$RESOLVED_VERSION)

  <!--
  ### Checklist for release
  - Download translations PR from Lokalize
  - Run ruff linter
  - Run make bump - select proper variant from Makefile
  - Review the draft below
  - Remove this checklist
  -->

  ## Notable Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "code quality"
    title:
      - "lint"
  - label: "translation"
    title:
      - "Lokalise:"
    files:
      - "**/translations/*.json"
  - label: "development tools"
    files:
      - ".devcontainer/*"
      - ".devcontainer.json"
      - "Makefile"
      - "setup.cfg"
      - "pyproject.toml"
      - ".github/*"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
